### ISSUE TITLE
API does not update in a timely fashion

### ISSUE THREAD

**Issue by BranchofLight** [peruukki/nhl-score-api#1]
As of posting, it is 5:07pm on Sunday March 4. Several games are already live, with several more scheduled for tonight. Despite this, the API still returns Saturday's games stats.

Is this a bug or is there a particular time the API updates?

**Comment by peruukki** [comment]
The API returns the scores from the latest night that has at least one finished game (see [the related test](https://github.com/peruukki/nhl-score-api/blob/master/test/nhl_score_api/fetchers/mlbam/latest_games_test.clj#L22)), so it was probably working as intended. The reasoning is that the API is written for [nhl-recap](http://peruukki.github.io/nhl-recap/) which would have nothing interesting to show if it received only unfinished games. The API also returns no scoring information for unfinished games, though that could probably be changed easily.

Do you have some use for this project or were you just curious? Now that you mentioned it, it would be nice to provide a way to get the scoring data as soon as it's available.

**Comment by BranchofLight** [comment]
I was previously using this project to grab teams playing today. I have since rewritten my project to use the NHL API directly to be sure of recency. 

I wanted to point it out in case that was undesirable. Thanks for the quick response.

**Comment by peruukki** [comment]
Ah cool, thanks for taking the time to point it out! And nice to hear this project was somewhat useful at one point. 😄

**Comment by peruukki** [comment]
I changed the behavior in commit 95a4566c7243e6311106fd69523d3db59c5ce34e, now the latest date's games are returned as soon as one of them has started.
