### ISSUE TITLE
Season's on! Not seeing any scores in /latest

### ISSUE THREAD

**Issue by ChrisArchitect** [peruukki/nhl-score-api#10]
Hi there,

Welcome to a new season! Not seeing any current game data in /scores/latest .... Hope you are still planning to run this server. Fire it up if so! (or wait til the 'real' start next week, all good I guess!) thx!

**Comment by peruukki** [comment]
Hello! Yeah, still planning to continue. 😄 Turns out the NHL API has moved the game stats behind another endpoint, and that caused an internal error. It will take some time to make the necessary changes, so for now, I changed this server to return zero values in the game stats.

**Comment by peruukki** [comment]
I got the game stats back, so things should be back to normal. 😌
