### ISSUE TITLE
Team name and location to details

### ISSUE THREAD

**Issue by ChrisArchitect** [peruukki/nhl-score-api#4]
Hi there

Happy new NHL Season :)

#Enhancement
Do you think you could add teamName ("Bruins") and locationName ("Boston") keys to the teams details section?

I know it will add to the data payload but useful to have those alongside abbreviation and id 

If not too much trouble, thanks!

**Comment by peruukki** [comment]
Hi, and happy new NHL season too! 😄 Yeah, that seems straightforward, I can add `shortName` too, useful if you need to show "NY Rangers" etc.
