### ISSUE TITLE
Undocumented behaviour: date can be null in /api/scores/latest

### ISSUE THREAD

**Issue by Hamatti** [peruukki/nhl-score-api#6]
The [docs say](https://github.com/peruukki/nhl-score-api#response-fields) that date field is `string` but it seems to be `null` for days when there are no games.

**Comment by peruukki** [comment]
Good point. 👍 Though looks like it's the whole `date` object that is `null` (and not its string fields), and that one is documented in the response documentation earlier in the docs. I'll add a mention of it in the relevant places, admittedly the documentation is a bit all over the place. 😄
