### ISSUE TITLE
Season 2020/2021 games are unobtainable

### ISSUE THREAD

**Issue by Darylsonn** [peruukki/nhl-score-api#7]
Trying to get games' data from any game of 2020/2021 season results in empty games array.
i.e nhl-score-api.herokuapp.com/api/scores?startDate=2021-01-19

**Comment by peruukki** [comment]
Ah, good catch. 👍 I'm seeing a server error related to standings when trying it out. I hadn't thought of past seasons, currently we always fetch the current standings. I'll try to fix this at some point before the new season starts.
