### ISSUE TITLE
Not seeing today's games in /scores/latest

### ISSUE THREAD

**Issue by ChrisArchitect** [peruukki/nhl-score-api#9]
Hi there,

Not seeing any current game data in /scores/latest .... Not sure if anything to do with your recent changes.  Maybe just a blip today, but heads up. Thanks!

**Comment by ChrisArchitect** [comment]
Working again as of about 1h20 later 👍

**Comment by peruukki** [comment]
Hi, thanks for reporting! I found an error in the caching logic that explains this, it's hopefully fixed now in d99718e8ef24740596c7209392eee7dd72abe1b8.
